name: 'npc_benchmark'
version: '1.0.0'
config-version: 2

profile: 'npc_benchmark'

model-paths: ["models"]
target-path: "target"
log-path: "logs"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # chemin vers les parquets silver, relatif au dossier depuis lequel `dbt run` est lancé
  # (dbt/npc_benchmark/), donc relatif à ce dossier
  silver_path: "../../data/silver"

models:
  npc_benchmark:
    staging:
      +materialized: view
    marts:
      +materialized: table
